import type { Metadata } from 'next';

import { bodyFont } from '@/app/fonts';
import '@/app/globals.css';
import ReactQueryProvider from '@/app/providers/react-query';

import { Footer } from '@/components/features/footer';
import { Navbar } from '@/components/features/navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark">
			<body className={bodyFont.className}>
				<ReactQueryProvider>
					<Navbar />
					{children}
					<Footer />
				</ReactQueryProvider>
			</body>
		</html>
	);
}
